### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by gerro-abarabar** [Luna5ama/FastMinecraft#1]
Please put on your readme.md on how to build.

Plus you could  also answer about the crashes.

**Comment by cWheme** [comment]
> Please put on your readme.md on how to build.
> 
> Plus you could also answer about the crashes.

I Agree

**Comment by Luna5ama** [comment]
> Please put on your readme.md on how to build.
> 
> Plus you could also answer about the crashes.

Please provide details about the crashes.

**Comment by gerro-abarabar** [comment]
How the hell am I going to tell you, I ain't no developer

**Comment by smallshen** [comment]
Are you black?

**Comment by Tarkan-Zarrouk** [comment]
wtf

**Comment by fuwuqihmr** [comment]
都是国人,没啥好装的(狗头保命)

**Comment by master7720** [comment]
> Are you black?

how did you know
