### ISSUE TITLE
1.16.5 forge when?

### ISSUE THREAD

**Issue by SpartanB312** [Luna5ama/FastMinecraft#2]
Good resolution for modpacks with massive mods. Can you plz optimize 1.16.5 forge?

**Comment by Tarkan-Zarrouk** [comment]
is hle going to be 1.16.5?!

**Comment by SpartanB312** [comment]
Can't wait for the 1.16.5 forge
impls to increase the FPS while playing a modpack called E6E.Those forge modpacks do really need this optimization .

**Comment by Luna5ama** [comment]
soon

**Comment by Luna5ama** [comment]
closed in e5ddd4f
